---
core_paths:
- "/api"
- "/users"
- "/omniauth_registrations"
- "/locale"
- "/meetings"
- "/decidim_awesome"
- "/account"
- "/conversations"
- "/notifications"
- "/notifications_settings"
- "/own_user_groups"
- "/data_portability"
- "/user_interests"
- "/groups"
- "/pages"
- "/search"
- "/static_map"
- "/404"
- "/500"
- "/follow"
- "/report"
- "/report_user"
- "/endorsements"
- "/amends"
- "/last_activities"
- "/system"
- "/admin"
verifications_paths:
- "/authorizations"
- "/id_documents"
- "/postal_letter"
- "/csv_census"
- "/sms"
space_index_paths:
- "/processes"
- "/assemblies"
- "/conferences"
